Added documentation #35
Agent-Hellboy/YouTubeDataApi_Wrapper pull request #37
Opened 2022-10-07 02:50 UTC by kailashchoudhary11

2022-10-07 05:31 UTC, Agent-Hellboy commented
please, add a description describing how to do that and how can someone build the doc and open it in the browser.

2022-10-07 05:38 UTC, kailashchoudhary11 commented
I think their [official documentation]  (https://www.sphinx-doc.org/en/master/tutorial/index.html) covers everything

2022-10-07 05:39 UTC, kailashchoudhary11 commented
I think their [official documentation](https://www.sphinx-doc.org/en/master/tutorial/index.html) explains everything!

2022-10-07 05:48 UTC, kailashchoudhary11 commented
The html files are included in docs/build/html/ directory. And if one want to make changes they can make changes in the .rst files included in the docs/source/ directory and then run `make html` in the docs/ directory.

2022-10-07 05:58 UTC, Agent-Hellboy commented
You should add the last comment in README

2022-10-07 06:49 UTC, kailashchoudhary11 commented
> You should add a new section as documentation in README, you can remove the example section from README

Okay Sure!

2022-10-07 06:52 UTC, kailashchoudhary11 commented
> You should add a new section as documentation in README, you can remove the example section from README

You mean i should remove all the codes from the Readme?

2022-10-07 07:07 UTC, Agent-Hellboy commented
> You mean i should remove all the codes from the Readme?

Yes, except the first example remove all.

2022-10-07 07:26 UTC, kailashchoudhary11 commented
> > You mean i should remove all the codes from the Readme?
> 
> Yes, except the first example remove all.

Please review!

2022-10-07 07:30 UTC, Agent-Hellboy commented
> Please review!

Thanks, I will review on weekends

2022-10-09 07:43 UTC, kailashchoudhary11 commented
@Agent-Hellboy Any updates?

2022-10-09 08:06 UTC, Agent-Hellboy requested changes
include files that are required to generate HTML and other files, no need to include the files generated by a sphinx, you can add instructions to generate HTML and other files.

2022-10-09 08:06 UTC, Agent-Hellboy commented on README.rst
> -
keep this in README

2022-10-09 08:06 UTC, Agent-Hellboy commented on README.rst
> -    >>> vid[0].get_description()
this one also and after that for other APIs, you can tell people to check doc.

2022-10-09 08:19 UTC, Agent-Hellboy commented
>@Agent-Hellboy Any updates?

added few comments, please check

2022-10-09 08:34 UTC, kailashchoudhary11 commented
> > @Agent-Hellboy Any updates?
> 
> added few comments, please check

Okay Sure!

2022-10-10 14:31 UTC, kailashchoudhary11 commented
Please Review @Agent-Hellboy

2022-10-10 17:33 UTC, Agent-Hellboy commented
Thanks for the PR @kailashchoudhary11

2022-10-10 17:34 UTC, merged